version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - redis
      - mysql
    networks:
      - backend
    network_mode: docker_network

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    network_mode: docker_network

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123456

    network_mode: docker_network

networks:
  backend: