version: "3"
services:

  go_docker:
    #build是通过指定dockerfile制作镜像
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    volumes:
      - "/data/go_docker/data/:/root/go_docker/data/"
  #    network_mode: "go_docker"


  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root123456"
      MYSQL_USER: "root"
      MYSQL_PASS: "root123456"
    #    network_mode: "go_docker"
    volumes:
      - "$PWD/data:/var/lib/mysql"

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
#    network_mode: "go_docker"

