// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterUserReq struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserReq) Reset()         { *m = RegisterUserReq{} }
func (m *RegisterUserReq) String() string { return proto.CompactTextString(m) }
func (*RegisterUserReq) ProtoMessage()    {}
func (*RegisterUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{0}
}

func (m *RegisterUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserReq.Unmarshal(m, b)
}
func (m *RegisterUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserReq.Marshal(b, m, deterministic)
}
func (m *RegisterUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserReq.Merge(m, src)
}
func (m *RegisterUserReq) XXX_Size() int {
	return xxx_messageInfo_RegisterUserReq.Size(m)
}
func (m *RegisterUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserReq proto.InternalMessageInfo

func (m *RegisterUserReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterUserRsp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRsp) Reset()         { *m = RegisterUserRsp{} }
func (m *RegisterUserRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRsp) ProtoMessage()    {}
func (*RegisterUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{1}
}

func (m *RegisterUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRsp.Unmarshal(m, b)
}
func (m *RegisterUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRsp.Marshal(b, m, deterministic)
}
func (m *RegisterUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRsp.Merge(m, src)
}
func (m *RegisterUserRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRsp.Size(m)
}
func (m *RegisterUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRsp proto.InternalMessageInfo

func (m *RegisterUserRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetUserReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserReq) Reset()         { *m = GetUserReq{} }
func (m *GetUserReq) String() string { return proto.CompactTextString(m) }
func (*GetUserReq) ProtoMessage()    {}
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{2}
}

func (m *GetUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReq.Unmarshal(m, b)
}
func (m *GetUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReq.Marshal(b, m, deterministic)
}
func (m *GetUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReq.Merge(m, src)
}
func (m *GetUserReq) XXX_Size() int {
	return xxx_messageInfo_GetUserReq.Size(m)
}
func (m *GetUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReq proto.InternalMessageInfo

func (m *GetUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetUserRsp struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRsp) Reset()         { *m = GetUserRsp{} }
func (m *GetUserRsp) String() string { return proto.CompactTextString(m) }
func (*GetUserRsp) ProtoMessage()    {}
func (*GetUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{3}
}

func (m *GetUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRsp.Unmarshal(m, b)
}
func (m *GetUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRsp.Marshal(b, m, deterministic)
}
func (m *GetUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRsp.Merge(m, src)
}
func (m *GetUserRsp) XXX_Size() int {
	return xxx_messageInfo_GetUserRsp.Size(m)
}
func (m *GetUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRsp proto.InternalMessageInfo

func (m *GetUserRsp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DelUserReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelUserReq) Reset()         { *m = DelUserReq{} }
func (m *DelUserReq) String() string { return proto.CompactTextString(m) }
func (*DelUserReq) ProtoMessage()    {}
func (*DelUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{4}
}

func (m *DelUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelUserReq.Unmarshal(m, b)
}
func (m *DelUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelUserReq.Marshal(b, m, deterministic)
}
func (m *DelUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelUserReq.Merge(m, src)
}
func (m *DelUserReq) XXX_Size() int {
	return xxx_messageInfo_DelUserReq.Size(m)
}
func (m *DelUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelUserReq proto.InternalMessageInfo

func (m *DelUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DelUserRsp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelUserRsp) Reset()         { *m = DelUserRsp{} }
func (m *DelUserRsp) String() string { return proto.CompactTextString(m) }
func (*DelUserRsp) ProtoMessage()    {}
func (*DelUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{5}
}

func (m *DelUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelUserRsp.Unmarshal(m, b)
}
func (m *DelUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelUserRsp.Marshal(b, m, deterministic)
}
func (m *DelUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelUserRsp.Merge(m, src)
}
func (m *DelUserRsp) XXX_Size() int {
	return xxx_messageInfo_DelUserRsp.Size(m)
}
func (m *DelUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DelUserRsp proto.InternalMessageInfo

func (m *DelUserRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Salary               int64    `protobuf:"varint,4,opt,name=salary,proto3" json:"salary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{6}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetSalary() int64 {
	if m != nil {
		return m.Salary
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterUserReq)(nil), "user.RegisterUserReq")
	proto.RegisterType((*RegisterUserRsp)(nil), "user.RegisterUserRsp")
	proto.RegisterType((*GetUserReq)(nil), "user.GetUserReq")
	proto.RegisterType((*GetUserRsp)(nil), "user.GetUserRsp")
	proto.RegisterType((*DelUserReq)(nil), "user.DelUserReq")
	proto.RegisterType((*DelUserRsp)(nil), "user.DelUserRsp")
	proto.RegisterType((*User)(nil), "user.User")
}

func init() { proto.RegisterFile("pb/user.proto", fileDescriptor_c4f917211a932270) }

var fileDescriptor_c4f917211a932270 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xed, 0x1f, 0x56, 0x1c, 0xff, 0x2d, 0x03, 0x4a, 0xe9, 0x61, 0x29, 0xf5, 0xe2, 0x41,
	0x76, 0x71, 0xbd, 0x7b, 0x12, 0xbc, 0x07, 0xfd, 0x00, 0x59, 0x76, 0x28, 0x85, 0x5d, 0x37, 0x66,
	0xea, 0xc1, 0x6f, 0xe4, 0xc7, 0x94, 0x4c, 0x52, 0x23, 0xa1, 0xe8, 0x6d, 0x3a, 0xef, 0xfd, 0x5e,
	0x93, 0x17, 0x38, 0x37, 0x9b, 0xd5, 0x07, 0x93, 0x5d, 0x1a, 0x7b, 0x18, 0x0e, 0x58, 0xba, 0xb9,
	0xbd, 0x87, 0x4b, 0x45, 0x5d, 0xcf, 0x03, 0xd9, 0x57, 0x26, 0xab, 0xe8, 0x1d, 0x17, 0x20, 0x52,
	0x95, 0x35, 0xd9, 0xed, 0xe9, 0x1a, 0x96, 0xc2, 0x88, 0xe8, 0x91, 0x9b, 0x04, 0x61, 0x83, 0x73,
	0x28, 0xf6, 0xdc, 0x09, 0x71, 0xa2, 0xdc, 0xd8, 0x36, 0x00, 0xcf, 0x34, 0x8c, 0x91, 0x08, 0xe5,
	0x9b, 0xde, 0x53, 0x30, 0xc8, 0xdc, 0xde, 0x45, 0x07, 0x9b, 0x7f, 0x7f, 0xda, 0x00, 0x3c, 0xd1,
	0xee, 0xaf, 0xbc, 0x45, 0x74, 0x4c, 0x9e, 0xe8, 0x05, 0x4a, 0x27, 0xe2, 0x05, 0xe4, 0xfd, 0x56,
	0x84, 0x42, 0xe5, 0xfd, 0xf6, 0x27, 0x2b, 0x8f, 0x59, 0x8e, 0xd6, 0x1d, 0x55, 0x85, 0x98, 0xdc,
	0x88, 0xd7, 0x30, 0x63, 0xbd, 0xd3, 0xf6, 0xb3, 0x2a, 0x65, 0x19, 0xbe, 0xd6, 0x5f, 0x99, 0x3f,
	0x38, 0x3e, 0xc2, 0xd9, 0xef, 0x56, 0xf0, 0xca, 0x5f, 0x21, 0x29, 0xb7, 0x9e, 0x5a, 0xb3, 0x69,
	0x8f, 0x70, 0x05, 0xc7, 0xa1, 0x0e, 0x9c, 0x7b, 0x4f, 0xec, 0xaf, 0x4e, 0x36, 0x23, 0x10, 0xee,
	0x3b, 0x02, 0xb1, 0xa0, 0x3a, 0xd9, 0x38, 0x60, 0x33, 0x93, 0x77, 0x7f, 0xf8, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0xd0, 0x18, 0x8f, 0x7e, 0x08, 0x02, 0x00, 0x00,
}
